### ISSUE TITLE
Please add support for Xiaomi Smartmi Evaporative Humidifier 2

### ISSUE THREAD

**Issue by jahnkenneth** [jghaanstra/com.xiaomi-miio#139]
Hello,

is it possible to add support for Xiaomi Smartmi Evaporative Humidifier 2?

![80FA56A1-88A8-4B73-93CC-ACD2AC0F8BE7](https://user-images.githubusercontent.com/28279147/103046115-57bf7a00-4587-11eb-9352-6ea1e57d0058.jpeg)

**Comment by jahnkenneth** [comment]
This project is clearly dead... No updates February.

**Comment by vladimir-maryenko** [comment]
Hi,

Having the same issue with the humidifier explained here https://community.athom.com/t/xiaomi-mi-home-app-for-wifi-devices/118/781?u=vladimir_m

The model name is “zhimi.humidifier.ca4” (CJXJSQ04ZM)

The problem is solved for Homebridge and explained here https://github.com/russtone/homebridge-mi-humidifier/issues/26

Can you please adapt the plugin to support that version at least on a basic level?

Thanks!

**Comment by jghaanstra** [comment]
Closing old issues. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
