### ISSUE TITLE
Tested with Roborock S5 Max (roborock.vacuum.s5e)

### ISSUE THREAD

**Issue by Arjan-21** [jghaanstra/com.xiaomi-miio#186]
Hi,

First of all I really like the update for the vacuum. Adding the sensor, filter and brush data is really clever and useful for me. 
I've tested the app for a few days, but for me there are a few bugs and I've a few questions. The action cards are working very good, but some of the triggers (IF cards) won't work.
Version of app: 3.1.16

1. The vacuum never turns on according to Homey. The two pictures are made almost on the same time, but there is a big difference. I use this allot, If the vacuum is vacuuming than it should be on and if it's charging/docked or stopped it should be off.
Old Roborock app
<img width=300 src="https://user-images.githubusercontent.com/75159756/228274991-17905fdf-5457-45a1-8571-2c32dfdcaaec.PNG">
Xiaomi Mi Home app
<img width=300 src="https://user-images.githubusercontent.com/75159756/228275019-03668046-6ebf-4aae-a9f8-783cdd88fa16.PNG">

2. the status is not updated. Not in the logic, but also not in the tile. however, the tile sometimes says stopped. Sorry the pictures are in dutch.
<img width=300 src="https://user-images.githubusercontent.com/75159756/228276778-a27af5b9-adf3-4ce6-8f3f-48dc45aa07d9.PNG">
<img width=300 src="https://user-images.githubusercontent.com/75159756/228276804-6b5be02b-8f22-44b4-9d36-11485109d1f2.PNG">
<img width=300 src="https://user-images.githubusercontent.com/75159756/228276826-1ff53bf4-32e1-4ecd-8db0-5eaf8a755499.jpeg">

3. I'm really happy about the trigger when the room layout is changed. But it's triggering every x seconds. Is there a way to only trigger it when the room is changed? 
3.1 A question about when the room layout is changed. It now sends a room ID with an XY coordinates. Is it possible to get only the ID? 
<img width="279" alt="Scherm­afbeelding 2023-03-14 om 17 17 47" src="https://user-images.githubusercontent.com/75159756/228278462-accdd00c-109a-466f-ba08-12ef5ce56db5.png">

4. Again a question. Is it possible to get the sensor, brush and filter data also as a logic variable?
<img width=300 src="https://user-images.githubusercontent.com/75159756/228278668-65e2063a-6101-4137-8e1f-27b0900e763c.jpeg">

Thanks again for your great app!

**Comment by jghaanstra** [comment]
First off all, send a diagnostic report from the app settings.

> The vacuum never turns on according to Homey. The two pictures are made almost on the same time, but there is a big difference. I use this allot, If the vacuum is vacuuming than it should be on and if it's charging/docked or stopped it should be off. Old Roborock app

The Roborock app is not developed by me and the code is not publically available. There will be differences on how this app functions and it's not specialized in supporting all specific models. Every model has differences making it hard to completely support all models and the generic driver will have trade offs for some devices. It could you are better of sticking with the Roborock app. Having said that, a possible source of issues is having the vacuum paired multiple times. It may not properly connect in either one of the apps at the same time.

> the status is not updated. Not in the logic, but also not in the tile. however, the tile sometimes says stopped. Sorry the pictures are in dutch.

Same as above, might be difference in the API of your model, might be because you are trying to read out the vacuum multiple times cause `busy` errors. A diagnostic report should tell more.

> I'm really happy about the trigger when the room layout is changed. But it's triggering every x seconds. Is there a way to only trigger it when the room is changed?

Will fix that with the next release.

> 3.1 A question about when the room layout is changed. It now sends a room ID with an XY coordinates. Is it possible to get only the ID?

I'm returning the value that is returned by the robot. As there is no documentation about this I cant be sure what is returned when so I would not know how to parse it to only return the ID without screwing it up for other models. You will need to parse it yourself in some advanced flow logic / homeyscript.

> Again a question. Is it possible to get the sensor, brush and filter data also as a logic variable?

This is already implemented, There are global tokens available under the app (not under the device).

I'll keep this open for now until there is a diagnostic report that might tell more about the first two issues.

**Comment by jghaanstra** [comment]
> The vacuum never turns on according to Homey. The two pictures are made almost on the same time, but there is a big difference. I use this allot, If the vacuum is vacuuming than it should be on and if it's charging/docked or stopped it should be off. Old Roborock app

> the status is not updated. Not in the logic, but also not in the tile. however, the tile sometimes says stopped. Sorry the pictures are in dutch.

This happens on zoned and segment cleaning only. Will be fixed in the next release.

**Comment by Arjan-21** [comment]
Here is the Diagnostic report: 48a7fa61-b2c4-4444-bd41-45bf6005f279

> The Roborock app is not developed by me and the code is not publically available. There will be differences on how this app functions and it's not specialized in supporting all specific models. Every model has differences making it hard to completely support all models and the generic driver will have trade offs for some devices. It could you are better of sticking with the Roborock app. Having said that, a possible source of issues is having the vacuum paired multiple times. It may not properly connect in either one of the apps at the same time.

I know this app works with toggles on and off, so I wanted to show the difference. 


> Will fix that with the next release.

Thank you!

> I'm returning the value that is returned by the robot. As there is no documentation about this I cant be sure what is returned when so I would not know how to parse it to only return the ID without screwing it up for other models. You will need to parse it yourself in some advanced flow logic / homeyscript.

Didn't know that's the input from the robot. Then adjusting it in logic is better.

> This is already implemented, There are global tokens available under the app (not under the device).

Thank you! Didn't notice that.

**Comment by Arjan-21** [comment]
> V3.1.17 Fix for triggering the room segment update trigger card for vacuum cleaners triggering every minute

Is working. Thank you!
