### ISSUE TITLE
Smartmi Standing Fan 3 (zhimi.fan.za5), Fanlevel, oscilation not working properly, ion function missing.

### ISSUE THREAD

**Issue by shikilee** [jghaanstra/com.xiaomi-miio#191]
I have this Smartmi Standing Fan 3 (zhimi.fan.za5) pair with "Mi Smart Standing Fan 3 (WIFI)".

Request for new device support for Smartmi Standing Fan 3 (zhimi.fan.za5)
Using "Mi Smart Standing Fan 3 (WIFI)", It is able to power on off but having some issues:

1/ Using mobile app not able to control fan speed (level) in 0-100% as the fan only respond to 4 level (1,2,3,4)
2/ Using Mobile app not able to control fan oscillation fan angle and oscillation On/off missing as fan have 4 Angles 丨Horizontal Oscillate 丨30°/60°/90°/120°
3/ ions on/off function missing.

Using Homey Dev tools able to control the fan
![image](https://user-images.githubusercontent.com/8916262/230260156-f83b29be-0178-4719-afdd-ba581d9cc6a7.png)

**Comment by jghaanstra** [comment]
> 1/ Using mobile app not able to control fan speed (level) in 0-100% as the fan only respond to 4 level (1,2,3,4)

That could to be a bug of the mobile app, the capability is configured to a dim slider with a range of 1, 2, 3 and 4. Did you actually check how the slider behaves and if it's possible to set values other than these 4 values?

> 2/ Using Mobile app not able to control fan oscillation fan angle and oscillation On/off missing as fan have 4 Angles 丨Horizontal Oscillate 丨30°/60°/90°/120°

* setting angle/oscillation  will be fixed with the next release
* oscillation On/off: this is named wrong as horizontal swing, will be fixed in next release

> 3/ ions on/off function missing.

Will be added with the next release.

All of this will be included in a new driver. On the next release you will need to re-pair your device and test again.

**Comment by jghaanstra** [comment]
The new driver is now available in the test channel with release 3.1.19. Please re-test.

**Comment by shikilee** [comment]
Hi Jelger,
I've tested with your latest release 3.1.19, re-pair with Smartmi Standing Fan 3. So far all the function is working great with iOS mobile app (7.0.0 (1177)). 
Perhaps if the GUI for Fanlevel able to improve, as current 0% = 1, 33% = 2, 67% = 3, 100% = 4.
It is possible to set min 25% , then follow by 50%, 75% and 100%?
See below sketches for explanations:
![IMG_1461](https://user-images.githubusercontent.com/8916262/230758562-84461acb-fd14-4beb-be19-eee387705083.jpg)

**Comment by jghaanstra** [comment]
I have no control over the UI elements. This is part of Homey SDK and not my app. Closing this as the bugs have been fixed.

**Comment by jghaanstra** [comment]
Thanx for the donation. Much appreciated.
