### ISSUE TITLE
Obtain Mi Home for Mi Vacuum 2nd gen returns two Tokens

### ISSUE THREAD

**Issue by Muto1899** [jghaanstra/com.xiaomi-miio#21]
Hi guys,

when I am following the  tutorial below (Non-Rooted Android Phones) I get two tokens back from SQLiteBrowser and neither one works. 

https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token_mirobot_new.md

My Vacuum is of the 2nd generation and Firmware is 3.3.9_001168. Both tokens do have 32 charakters.
Any idea, what might be the problem?

Thanks,
Muto

**Comment by jghaanstra** [comment]
I dont have a 2nd gen robot so I'm not sure why it would return two tokens. You say they dont work but the code in this repository does not support the 2nd gen robot. In fact it does not support the first gen anymore as well because of time out issues with more recent firmwares of the robot. So that may very well be the case for you as well.

To figure out why it returns two tokens you would have use sqlitebrowser to view the devicerecord table instead of just selecting one (or in your case) two records. Just view to table and see which devices are registered and what tokens are registered with these devices.
