### ISSUE TITLE
Xiaomi smart purifier elite doesnt work

### ISSUE THREAD

**Issue by thomaswitt** [jghaanstra/com.xiaomi-miio#234]
I am looking for support for the https://www.mi.com/global/product/xiaomi-smart-air-purifier-elite/

**Comment by jghaanstra** [comment]
Read this and silly the required information or a device to test with.

https://github.com/jghaanstra/com.xiaomi-miio/wiki/Adding-new-devices

**Comment by jghaanstra** [comment]
Please test release 3.2.15 which is pending approval by Athom in the app store.

https://homey.app/a/com.xiaomi-miio/test/

https://github.com/jghaanstra/com.xiaomi-miio/wiki/Supported-Devices

**Comment by jghaanstra** [comment]
Closing this due to lack of response.

**Comment by thomaswitt** [comment]
@jghaanstra – Sorry for the delay and thank you for your effort! I set it up with 3.2.16, the setup process actually worked - but device modes (on/off/auto) are not recognized and I don't get any readings like PM2.5

**Comment by jghaanstra** [comment]
Please send a diagnostic report from the app settings.

**Comment by jghaanstra** [comment]
The next release will contain a possible fix.

**Comment by jghaanstra** [comment]
Please test release 3.2.17 which might contain a fix. The release is pending approval by Athom in the app store but you can test it through the test channel

https://homey.app/a/com.xiaomi-miio/test/

**Comment by thomaswitt** [comment]
Just tested it. Better, but not perfect yet.

- Switching on/off works
- PM2.5 display works

What's broken:
- Fan modes. Auto and EMPTY does nothing, Night switches to Mode ~, Favorite to Mode ~~ and Idle to mode ~~~. Night mode is not able to be activated.

What's missing:
- Changing the display brightness (On/Dim/Off)
- Manual Mode in Fan modes with setting the fan speed with a slider

I hope that helps…

**Comment by jghaanstra** [comment]
About the mode. There could be differences in what the title says and what mode is actually switched. This driver supports a lot of airpurifier and Xiaomi doesnt really follow a standard. It's impossible to implement every variation. That said, the documentation [here](https://home.miot-spec.com/spec/zhimi.airp.meb1) implies there are still 4 modes ranging from 0 to 3. That does not explain why some of the modes do nothing so that documentation may be incorrect. Not much I can do about.  If you want this fixed you will need to supply the correct miot details of this device (or donate the actual device) yourself.

The screen brightness is available as a on-off setting under the device settings.

If you can confirm that manual fan speed corresponds to value siid 9-1 (called moto-speed-rpm) [here](https://miot-spec.org/miot-spec-v2/spec/property?type=urn:zhimi-spec:property:moto-speed-rpm:00000001) I might consider implementing it.

**Comment by thomaswitt** [comment]
Link is broken - would you be so kind to correct it?

**Comment by thomaswitt** [comment]
Hi,

thnks for sharking the spec. I think I see the problem.

In the spec, the Mode is PIID 4 (0 - Auto // 1 - Sleep // 2 - Favorite // 3 - Manual), but in the code [it is mapped to PIID 5 (Line 243](https://github.com/jghaanstra/com.xiaomi-miio/blob/master/drivers/airpurifier_zhimi_advanced_miot/device.js?plain=1#L243). You just forgot to change the set_properties accordingly.

I made [a pull request](https://github.com/jghaanstra/com.xiaomi-miio/pull/243) to correct this.

**Comment by jghaanstra** [comment]
Thanx, I'll change that locally instead of merging the PR. It will be included in the next release. If that will fix the mode issue remains to be seen then.

**Comment by jghaanstra** [comment]
This fix is included in release 3.2.18 which is currently pending Athom's approval in the app store. You can test it by installing the test version.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by thomaswitt** [comment]
Tested and it works. 🚀Thanks a lot for your time and your work. 🙏🏻

Regarding my other question, I'd like to change the display brightness via a "Then..." card (currently only possible via preferences) - should I open another issue for that?

**Comment by jghaanstra** [comment]
> Regarding my other question, I'd like to change the display brightness via a "Then..." card (currently only possible via preferences) - should I open another issue for that?

Please do.
