### ISSUE TITLE
Mi Robot Vacuum Cleaner, status bug 

### ISSUE THREAD

**Issue by robiebab** [jghaanstra/com.xiaomi-miio#24]
if you activate(stofzuigen) the Mi Robot vacuum cleaner it changes the status (thats ok), except if the app polls in between it gives again the old status (charging). 

I think there needs to be a poll timout of +- 60sec (best gues) after changing the status with a flow or app, or ofcourse if there is a better solution.

**Comment by jghaanstra** [comment]
Did you test this with the version currently available in the app store or did you test the version available here on GitHub with a CLI install?

**Comment by robiebab** [comment]
The newest version with cli

**Comment by jghaanstra** [comment]
The miio library is responsible for tracking the actual status of the Mi Robot. If it changes back to charging after being updated in Homey by flow or app this means that the miio library has not updated the robot status within the miio device object (and thus changes it back when polling by Homey takes place which reads the miio device status). The way I currently retrieve the status is already somewhat hacky because I'm accessing the raw miio device object. I have discussed this with the author of the library but there currently is no other way in this version of the library (where it was available under 0.14.x).

Temporary disabling polling in my app would be a nasty workaround for this. I'd rather open the discussion again about the tracking of the device status by the miio library. You can track it here: https://github.com/aholstenson/miio/issues/107

**Comment by jghaanstra** [comment]
Most likey fixed with https://github.com/jghaanstra/com.xiaomi-miio/commit/c9e7145b1a8475f6284ba4addd1910d23e8c89aa

Please open the issue again if the problem persists. The release will be pushed to the app store as well.
