### ISSUE TITLE
[Bug] Sometimes commands to miio device time out and need to be repeated

### ISSUE THREAD

**Issue by robiebab** [jghaanstra/com.xiaomi-miio#27]
Sometimes the vacuum cleaner won't accepts commands to the vacuum cleaner, after i resend the command it runs

<img width="1270" alt="schermafbeelding 2018-03-21 om 15 11 43" src="https://user-images.githubusercontent.com/18186327/37714833-d00a231c-2d1a-11e8-8656-6f695bc2b1e5.png">

**Comment by jghaanstra** [comment]
I have noticed this myself but there is not much I can do, I dont want to hard code sending multiple commands. I think it might be related to the way the previous time out issues have been solved. The author of the miio library has quick fixed these previous time out issue by generating a unique request token for when the initial request has failed. A proper fix would be to generate a request token for each request, including the initial request.

**Comment by TheArcturian** [comment]
I have the same problem, but sometimes it does not help resending it. 

Also when I test the flow in Homey, it usually works, but when the flow is running because it gets triggered normally in Homey, it does nothing. A very seldom time, it acctually works.

It would be great if you could actually fix this as I cannot use the app in flows like it is now. Thanks!
