### ISSUE TITLE
Support for Xiaomi Mi Plant

### ISSUE THREAD

**Issue by Rido** [jghaanstra/com.xiaomi-miio#3]
It would be great if you could add support for the Xiaomi Mi Plant device.

For example with the triggers:
1. Plant X needs water.
2. Plant Y needs fertilizer.

There's a existing [library](https://github.com/open-homeautomation/miflora) for the Mi Plant. Maybe you could use that one.

Thanks and great work! 😉

**Comment by jghaanstra** [comment]
Hello @Rido,

The Xiaomi Mi Flora plant sensor is a bluetooth device instead of a Wi-Fi device. Currently support for bluetooth is very limited within Homey. Once bluetooth gains proper support I might look into supporting Xiaomi Mi bluetooth devices like the Xiaomi Mi Flora plant sensor.

For now I'm closing this issue.
