### ISSUE TITLE
Yeelight status not reporting

### ISSUE THREAD

**Issue by moment77** [jghaanstra/com.xiaomi-miio#56]
Homey: v1.5.12
Xiaomi Mi Home: v2.9.0

I've discovered that my Yeelights does not report status. If I turn off a bulb via Homey desktop app, it doesn't update it status in mobile app or vice versa. If I turn off a bulb via a flow, it does not update the bulbs status in neither app och desktop app. All commands work though.

**Comment by jghaanstra** [comment]
Curious, just tested this myself and it works fine for me. Could you tell me which mobile app you are using (iOS or Android and regular or beta).

And could you restart the Xiaomi Mi Home app within Homey and try again to see if it still does not update the status of your Yeelight(s).

And last, could you tell me what Yeelight bulbs you have.

**Comment by chinswain** [comment]
I have a similar issue although intermittent.

I have quite a few ceiling lights around the house - I switched from using a Boolean variable to the lights actual status so that I could use the Yeelights bluetooth remote (via the "is turned on\off cards). Multiple times a week the light status returns off when the light is actually on.

**Comment by jghaanstra** [comment]
That's might be a different issue @chinswain .  This original issue seems to be about syncing the device status within the Homey eco system while your issue might be related to updating the device status when it's changed from outside the Homey eco system.

The way the app works is by registering a connection between Homey and every devices and listen to notify events when the status of the light changes. When this status is not send, not recieved or not parsed correctly by my app it will get out of sync. I'm a lousy coder so that could surely be the reason but I cant really tell since I cant reproduce. What you could do is run the app through CLI install and have it run a little while and see what the logs spits out. That might give me some indication of what is going on.

**Comment by jghaanstra** [comment]
@moment77 are you using "the turn the light on" and "turn the light off card" or "the toggle the light card" or does this happen with all these cards? And does it never update the status when using one of these flow cards or only sometimes?

And could you check the following, have a flow switch the state of the light while you have the mobile app and/or webinterface open while watching the device. I'd like to know if you see it change state but directly change it back again (to the incorrect state).

**Comment by jghaanstra** [comment]
Closed due to inactivity. Feel free to comment if you still want to try to debug this.
