### ISSUE TITLE
Yeelight LEDstrip not found (anymore)

### ISSUE THREAD

**Issue by Vgsjovik** [jghaanstra/com.xiaomi-miio#79]
I have a Yeelight LEDstrip installed in a tall cabinet in my kitchen. Controlled with Homey and a Aqara motion sensor. After the last update it stopped working. The flow does not work, and I am not able to find it in (it add it) my list of devices. 
Everything is updated with latest software/firmware. (And LAN-controll is activated). 
It works with the Yeelight app, just as before.

**Comment by jghaanstra** [comment]
Could you try and reboot the Homey Mi Home app and try again.

**Comment by Vgsjovik** [comment]
Wow! 
That was quick! 

I have tried restarting the app and Homey.
And I have uninstalled and installed the app again.

**Comment by jghaanstra** [comment]
You say you can not find your LED strip in the list of devices. But you do have a flow with an action card for your LED strip? That card should have the name of your device and would help you search for it. If it's still added to Homey it's normal that it will not show up while pairing since it's already paired. Your restarts should make sure the device is also controllable again if it was still added. Could you explain a bit more about if you actually removed the device.

**Comment by jghaanstra** [comment]
I see I introduced a bug when pairing Yeelights. I'll submit a fix later this evening, hopefully it will be approved soon.

**Comment by jghaanstra** [comment]
Fixed with release 2.11.3.

https://github.com/jghaanstra/com.xiaomi-miio/releases/tag/2.11.3

**Comment by Vgsjovik** [comment]
Hi! 
I don’t know if i can answer this when the case is closed. 
I am very impressed with your work and your response time! 
Before I contacted you I posted my problem in a Norwegian Homey group. It is a great community with a lot of helpful people. 

Thank you for handling this case so quickly! Keep up the good work!

-Vegard

**Comment by jghaanstra** [comment]
Good to hear and thank you for your donation. It's much appreciated!

**Comment by Vgsjovik** [comment]
The app was update this evening, as you probably know. It worked perfectly!

Great work! 

-Vegard
